// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: MonitorPC

#ifndef _MONITORPC_UI_H
#define _MONITORPC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenCPU
void ui_ScreenCPU_screen_init(void);
void ui_event_ScreenCPU(lv_event_t * e);
extern lv_obj_t * ui_ScreenCPU;
extern lv_obj_t * ui_CPUPanelOjos;
extern lv_obj_t * ui_CPUPanelBoca;
extern lv_obj_t * ui_CPUImageFondo;
extern lv_obj_t * ui_CPUArcTemp;
extern lv_obj_t * ui_CPULabelTemp;
extern lv_obj_t * ui_CPUArcVent1;
extern lv_obj_t * ui_CPULabelVent1;
extern lv_obj_t * ui_CPUArcVent2;
extern lv_obj_t * ui_CPULabelVent2;
extern lv_obj_t * ui_CPULabelLoad;
extern lv_obj_t * ui_CPULabelLoadText;
extern lv_obj_t * ui_CPUPanelTouch;
// SCREEN: ui_ScreenGPU
void ui_ScreenGPU_screen_init(void);
void ui_event_ScreenGPU(lv_event_t * e);
extern lv_obj_t * ui_ScreenGPU;
extern lv_obj_t * ui_GPUPanelOjos1;
extern lv_obj_t * ui_GPUPanelBoca1;
extern lv_obj_t * ui_GPUImageFondo;
void ui_event_GPUArcTemp(lv_event_t * e);
extern lv_obj_t * ui_GPUArcTemp;
extern lv_obj_t * ui_GPULabelTemp;
extern lv_obj_t * ui_GPUArcVent1;
extern lv_obj_t * ui_GPULabelVent1;
extern lv_obj_t * ui_GPULabelLoad;
extern lv_obj_t * ui_GPULabelLoadText;
extern lv_obj_t * ui_GPUPanelTouch;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_z2_png);    // assets/z2.png



LV_FONT_DECLARE(ui_font_Font3270T24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
