// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: MonitorPC

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelOjos = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelOjos, 74);
    lv_obj_set_height(ui_PanelOjos, 27);
    lv_obj_set_x(ui_PanelOjos, -3);
    lv_obj_set_y(ui_PanelOjos, 15);
    lv_obj_set_align(ui_PanelOjos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelOjos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelBoca = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelBoca, 51);
    lv_obj_set_height(ui_PanelBoca, 27);
    lv_obj_set_x(ui_PanelBoca, -2);
    lv_obj_set_y(ui_PanelBoca, 61);
    lv_obj_set_align(ui_PanelBoca, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBoca, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageFondo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageFondo, &ui_img_z2_png);
    lv_obj_set_width(ui_ImageFondo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageFondo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageFondo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageFondo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageFondo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ImageFondo, &ui_img_z2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ImageFondo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ImageFondo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcTemp, 230);
    lv_obj_set_height(ui_ArcTemp, 230);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcTemp, 1);
    lv_arc_set_bg_angles(ui_ArcTemp, 284, 180);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0x2F2F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFF4440), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, 40);
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -5);
    lv_obj_set_y(ui_LabelTemp, -109);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "000");
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcVent1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcVent1, 200);
    lv_obj_set_height(ui_ArcVent1, 200);
    lv_obj_set_align(ui_ArcVent1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcVent1, 500, 1800);
    lv_arc_set_value(ui_ArcVent1, 510);
    lv_arc_set_bg_angles(ui_ArcVent1, 285, 180);
    lv_obj_set_style_arc_color(ui_ArcVent1, lv_color_hex(0x2F2F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVent1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcVent1, lv_color_hex(0x2A04FB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVent1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcVent1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcVent1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelVent1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelVent1, 40);
    lv_obj_set_height(ui_LabelVent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVent1, -5);
    lv_obj_set_y(ui_LabelVent1, -92);
    lv_obj_set_align(ui_LabelVent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVent1, "0000");
    lv_obj_set_style_text_align(ui_LabelVent1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcVent2 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcVent2, 170);
    lv_obj_set_height(ui_ArcVent2, 170);
    lv_obj_set_align(ui_ArcVent2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcVent2, 450, 1850);
    lv_arc_set_value(ui_ArcVent2, 460);
    lv_arc_set_bg_angles(ui_ArcVent2, 288, 180);
    lv_obj_set_style_arc_color(ui_ArcVent2, lv_color_hex(0x2F2F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVent2, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcVent2, lv_color_hex(0x04EFFB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVent2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcVent2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcVent2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelVent2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelVent2, 40);
    lv_obj_set_height(ui_LabelVent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVent2, -5);
    lv_obj_set_y(ui_LabelVent2, -75);
    lv_obj_set_align(ui_LabelVent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVent2, "0000");
    lv_obj_set_style_text_align(ui_LabelVent2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCPULoad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCPULoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCPULoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCPULoad, 0);
    lv_obj_set_y(ui_LabelCPULoad, 8);
    lv_obj_set_align(ui_LabelCPULoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCPULoad, "8.8");
    lv_obj_set_style_text_align(ui_LabelCPULoad, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCPULoad, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLoad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoad, -1);
    lv_obj_set_y(ui_LabelLoad, -21);
    lv_obj_set_align(ui_LabelLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoad, "LOAD");
    lv_obj_set_style_text_color(ui_LabelLoad, lv_color_hex(0x05F3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoad, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
