// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: MonitorPC

#include "../ui.h"

void ui_ScreenTime_screen_init(void)
{
    ui_ScreenTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeImageFondo = lv_img_create(ui_ScreenTime);
    lv_img_set_src(ui_TimeImageFondo, &ui_img_z2_png);
    lv_obj_set_width(ui_TimeImageFondo, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_TimeImageFondo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeImageFondo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeImageFondo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TimeImageFondo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TimeImageFondo, &ui_img_z2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_TimeImageFondo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_TimeImageFondo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_ScreenTime);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -2);
    lv_obj_set_y(ui_LabelTime, -86);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "00:00:00");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_ScreenTime);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 0);
    lv_obj_set_y(ui_LabelDate, 63);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, " 00/00/0000");
    lv_obj_set_style_text_align(ui_LabelDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenTime, ui_event_ScreenTime, LV_EVENT_ALL, NULL);

}
