// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: MonitorPC

#include "../ui.h"

void ui_ScreenCPUHist_screen_init(void)
{
    ui_ScreenCPUHist = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCPUHist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CPUHistImageFondo = lv_img_create(ui_ScreenCPUHist);
    lv_img_set_src(ui_CPUHistImageFondo, &ui_img_z2_png);
    lv_obj_set_width(ui_CPUHistImageFondo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPUHistImageFondo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CPUHistImageFondo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CPUHistImageFondo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CPUHistImageFondo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CPUHistImageFondo, &ui_img_z2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_CPUHistImageFondo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartCPU = lv_chart_create(ui_ScreenCPUHist);
    lv_obj_set_width(ui_ChartCPU, 180);
    lv_obj_set_height(ui_ChartCPU, 180);
    lv_obj_set_align(ui_ChartCPU, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartCPU, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ChartCPU, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartCPU, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 30);
    lv_chart_set_axis_tick(ui_ChartCPU, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ChartCPU_series_1 = lv_chart_add_series(ui_ChartCPU, lv_color_hex(0xED0A0A),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartCPU_series_1_array[] = { 20, 12, 35, 80, 90, 50, 40, 40, 30, 25 };
    lv_chart_set_ext_y_array(ui_ChartCPU, ui_ChartCPU_series_1, ui_ChartCPU_series_1_array);
    lv_chart_series_t * ui_ChartCPU_series_2 = lv_chart_add_series(ui_ChartCPU, lv_color_hex(0x1418E4),
                                                                   LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartCPU_series_2_array[] = { 40, 32, 45, 58, 65, 50, 45, 45, 30, 41 };
    lv_chart_set_ext_y_array(ui_ChartCPU, ui_ChartCPU_series_2, ui_ChartCPU_series_2_array);
    lv_obj_set_style_bg_color(ui_ChartCPU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartCPU, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChartCPU, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartCPU, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);


    lv_obj_set_style_line_color(ui_ChartCPU, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartCPU, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartCPU, 1, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ChartCPU, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartCPU, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartCPU, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenCPUHist, ui_event_ScreenCPUHist, LV_EVENT_ALL, NULL);

}
