// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: MonitorPC

#ifndef _MONITORPC_UI_H
#define _MONITORPC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PanelOjos;
extern lv_obj_t * ui_PanelBoca;
extern lv_obj_t * ui_ImageFondo;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_ArcVent1;
extern lv_obj_t * ui_LabelVent1;
extern lv_obj_t * ui_ArcVent2;
extern lv_obj_t * ui_LabelVent2;
extern lv_obj_t * ui_LabelCPULoad;
extern lv_obj_t * ui_LabelLoad;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_z2_png);    // assets\z2.png

LV_FONT_DECLARE(ui_font_Font3270T24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
