// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: MonitorPC

#include "../ui.h"

void ui_ScreenGPU_screen_init(void)
{
    ui_ScreenGPU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGPU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPUPanelOjos1 = lv_obj_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPUPanelOjos1, 74);
    lv_obj_set_height(ui_GPUPanelOjos1, 27);
    lv_obj_set_x(ui_GPUPanelOjos1, -3);
    lv_obj_set_y(ui_GPUPanelOjos1, 15);
    lv_obj_set_align(ui_GPUPanelOjos1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPUPanelOjos1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPUPanelBoca1 = lv_obj_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPUPanelBoca1, 51);
    lv_obj_set_height(ui_GPUPanelBoca1, 27);
    lv_obj_set_x(ui_GPUPanelBoca1, -2);
    lv_obj_set_y(ui_GPUPanelBoca1, 61);
    lv_obj_set_align(ui_GPUPanelBoca1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPUPanelBoca1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPUImageFondo = lv_img_create(ui_ScreenGPU);
    lv_img_set_src(ui_GPUImageFondo, &ui_img_z2_png);
    lv_obj_set_width(ui_GPUImageFondo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPUImageFondo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GPUImageFondo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GPUImageFondo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GPUImageFondo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_GPUImageFondo, &ui_img_z2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_GPUImageFondo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_GPUImageFondo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPUArcTemp = lv_arc_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPUArcTemp, 230);
    lv_obj_set_height(ui_GPUArcTemp, 230);
    lv_obj_set_align(ui_GPUArcTemp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_GPUArcTemp, 1);
    lv_arc_set_bg_angles(ui_GPUArcTemp, 284, 180);
    lv_obj_set_style_arc_color(ui_GPUArcTemp, lv_color_hex(0x2F2F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPUArcTemp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GPUArcTemp, lv_color_hex(0xFF4440), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPUArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GPUArcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPUArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_GPULabelTemp = lv_label_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPULabelTemp, 40);
    lv_obj_set_height(ui_GPULabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPULabelTemp, -5);
    lv_obj_set_y(ui_GPULabelTemp, -109);
    lv_obj_set_align(ui_GPULabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPULabelTemp, "000");
    lv_obj_set_style_text_align(ui_GPULabelTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPUArcVent1 = lv_arc_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPUArcVent1, 200);
    lv_obj_set_height(ui_GPUArcVent1, 200);
    lv_obj_set_align(ui_GPUArcVent1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_GPUArcVent1, 500, 1800);
    lv_arc_set_value(ui_GPUArcVent1, 510);
    lv_arc_set_bg_angles(ui_GPUArcVent1, 285, 180);
    lv_obj_set_style_arc_color(ui_GPUArcVent1, lv_color_hex(0x2F2F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPUArcVent1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GPUArcVent1, lv_color_hex(0x2A04FB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPUArcVent1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GPUArcVent1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPUArcVent1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_GPULabelVent1 = lv_label_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPULabelVent1, 40);
    lv_obj_set_height(ui_GPULabelVent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPULabelVent1, -5);
    lv_obj_set_y(ui_GPULabelVent1, -92);
    lv_obj_set_align(ui_GPULabelVent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPULabelVent1, "0000");
    lv_obj_set_style_text_align(ui_GPULabelVent1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPULabelLoad = lv_label_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPULabelLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPULabelLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPULabelLoad, 0);
    lv_obj_set_y(ui_GPULabelLoad, 8);
    lv_obj_set_align(ui_GPULabelLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPULabelLoad, "8.8");
    lv_obj_set_style_text_align(ui_GPULabelLoad, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPULabelLoad, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPULabelLoadText = lv_label_create(ui_ScreenGPU);
    lv_obj_set_width(ui_GPULabelLoadText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPULabelLoadText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPULabelLoadText, -1);
    lv_obj_set_y(ui_GPULabelLoadText, -21);
    lv_obj_set_align(ui_GPULabelLoadText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPULabelLoadText, "GPU LOAD");
    lv_obj_set_style_text_color(ui_GPULabelLoadText, lv_color_hex(0x05F3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GPULabelLoadText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPULabelLoadText, &ui_font_Font3270T24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
